apiVersion: v1
kind: Service
metadata:
  name: diamondappdeployment
spec:
  selector:
    app: diamondappdeployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer