name: Deployment of node.js app into aws-eks
on:
   push:
      branches: ["main"]
   pull_request:
      branches: ["main"]

jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Github checkout
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
           version: 'v1.24.0' # default is latest stable
        id: install

      - name: Aws configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
           aws-region: us-east-1

      - name: Aws ecr loggin
        id: loggin-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get commit hash
          id: get-commit-hash
          run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"

      - name: Get timestamp
          id: get-timestamp
          run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d-%H-%M')"
        
      - name: Build, tag, and push the image to Amazon ECR
          id: build-image
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
            IMAGE_TAG: ${{ steps.get-commit-hash.outputs.commit-hash }}-${{ steps.get-timestamp.outputs.timestamp }}
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update kube config
        run: aws eks update-kubeconfig --name eks-cluster-110
    
      - name: Deploy to AWS-EKS
        run: |
           kubectl apply -f deployment.yaml
           kubectl apply -f service.yaml     