name: Deployment of node.js app into aws-eks
0n:
   push:
      branches: ["main"]
   pull_request:
      branches: ["main"]

jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Github checkout
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
           version: 'v1.24.0' # default is latest stable
        id: install

      - name: Aws configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
           aws-region: us-east-1

      - name: Aws ecr loggin
        id: loggin-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build docker image to push to aws ecr
        env:
           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           REPOSITORY: preye-ecr
           IMAGE_TAG: 1.5
        run: |
           docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
           docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Update kube config
        run: aws eks update-kubeconfig --name eks-cluster-110
    
      - name: Deploy to AWS-EKS
        run: |
           kubectl apply -f deployment.yaml
           kubectl apply -f service.yaml     